### ISSUE TITLE
LaTeX/TikZ output appears to be missing required style definitions

### ISSUE THREAD

**Issue by pseudoacacia** [cristianochesi/e-MGs#2]
The LaTeX/TikZ output from this script is a `forest` environment, but it uses three style keys that appear to have no definition: `index`, `outdex`, and `move=canonical`.

Would you be able to share how those are expected to be defined? 

Thanks.

**Comment by cristianochesi** [comment]
This is an example of a full-fledged .tex file with styles defined (these are taken from Graf et al. 2017) - adding this to next release, thanks (remember not to leave empty lines between "]" and "\draw"...)
[sample_forest_tree.zip](https://github.com/cristianochesi/e-MGs/files/9206718/sample_forest_tree.zip)
